"""A Game resource, as the editor uses it: its modules (the commands the AI uses; they say which Game they work on: the project has no Game of its own, every Level names the one it
runs under) and that an old Script.config.txt is not read any more.

The compilers are tested apart (test_game_compiler.py, test_script_module_compiler.py); these tests drive the editor with its resource pipeline.
"""
import re
import secrets
import time

import pytest

from harness import Editor, DEFAULT_EXE, REPO, SMOKE_DIR, quote
from script_project import CMAKELISTS, GAME_ASSET, MODULE_DESCRIPTOR, MODULE_GUID, PROJECT, game_folder, game_project_text, new_asset, remove_asset, wait_for_pipeline

MODULE_TYPE = "8D3968CB1287FA04"
GAME_TYPE = "A3F1D6C0452E9B17"
FOLDER_TYPE = "C4D90C5F0CC43021"
SCRIPT_CONFIG = PROJECT / "Project.config" / "Script.config.txt"
MODULE_ASSET = f"{MODULE_GUID}{MODULE_TYPE}"


@pytest.fixture
def lib(editor):
    return editor.libraries()[0][0]


def project_game(editor, game=GAME_ASSET):
    """(game asset guid or None, [module asset guids]) from ListProjectModuleReferences."""
    lines = editor.cmd(f"ListProjectModuleReferences -Game {game}").splitlines()
    game = re.match(r"Game: (\w{32})", lines[0])
    return (game[1] if game else None), [l for l in lines[1:] if re.fullmatch(r"\w{32}", l)]


def test_a_game_resource_lists_its_modules(editor):
    game, modules = project_game(editor)
    assert game and game.endswith(GAME_TYPE), "the Game the Soccer level names is a Game resource"
    assert MODULE_ASSET in modules, "the example project's game is made of the SoccerGame module"
    assert (game_folder() / "Descriptor.txt").is_file()


def test_the_game_project_is_made_by_the_pipeline_from_the_game_and_its_modules(editor):
    text = game_project_text()
    assert "Generated by the Game compiler" in text and f"# module {MODULE_GUID}" in text
    assert f"ScriptModule/A5/B1/{MODULE_GUID}" in text, "the project includes the CMake file of the module"
    assert str(PROJECT).replace("\\", "/") not in CMAKELISTS.read_text().replace("\\", "/"), "the project names no place: it is the same on every machine"


def test_a_module_added_to_the_game_is_in_the_project_and_the_undo_takes_it_out(editor, lib):
    module = new_asset(editor, lib, MODULE_TYPE, f"Scratch{secrets.token_hex(2)}")
    stem = f"scratch_{secrets.token_hex(2)}"
    try:
        assert editor.cmd(f"AddScriptSourceFile -Library {lib} -Asset {module} -FileName {stem}.cpp", allow_disk=True) == "", "a module gets its Descriptor.txt with its first file"
        assert editor.cmd(f"AddProjectModuleReference -Module {module} -Game {GAME_ASSET}", allow_disk=True) == ""
        assert project_game(editor)[1] == [MODULE_ASSET, module], "the module is listed after the ones that were there"
        assert editor.cmd(f"AddProjectModuleReference -Module {module} -Game {GAME_ASSET}", allow_disk=True) == "", "adding it again changes nothing"
        assert project_game(editor)[1].count(module) == 1
        value = int(module[:16], 16)
        rest = f"ScriptModule/{value & 0xFF:02X}/{(value >> 8) & 0xFF:02X}/{value:X}"
        fragment = PROJECT / "Cache" / "Resources" / "Platforms" / "WINDOWS" / rest
        deadline = time.time() + 60
        while time.time() < deadline and rest not in CMAKELISTS.read_text().replace("\\", "/"):
            time.sleep(0.25)
        assert rest in CMAKELISTS.read_text().replace("\\", "/"), "the pipeline made the project again with the new module in it"
        assert f"{stem}.cpp" in fragment.read_text(), "from the CMake file the pipeline compiled for the module"
        editor.cmd("Undo"); editor.cmd("Undo")                     # the second add changed nothing and is an undo step of its own
        assert project_game(editor)[1] == [MODULE_ASSET], "the undo took the module out of the game"
        editor.cmd("Redo"); editor.cmd("Redo")
        assert project_game(editor)[1] == [MODULE_ASSET, module], "and the redo put it back"
        assert editor.cmd(f"RemoveProjectModuleReference -Module {module} -Game {GAME_ASSET}", allow_disk=True) == ""
        assert project_game(editor)[1] == [MODULE_ASSET]
        assert "not a module reference of that Game" in editor.cmd(f"RemoveProjectModuleReference -Module {module} -Game {GAME_ASSET}", allow_disk=True)
    finally:
        editor.cmd(f"RemoveProjectModuleReference -Module {module} -Game {GAME_ASSET}", allow_disk=True)
    wait_for_pipeline(120)
    assert f"/{int(module[:16], 16):X}\"" not in CMAKELISTS.read_text(), "and the project is made again without it"
    remove_asset("ScriptModule", module)


def test_a_guid_that_is_not_a_module_is_refused(editor):
    assert "not a Script-Module" in editor.cmd(f"AddProjectModuleReference -Module 0000000000000001{GAME_TYPE} -Game {GAME_ASSET}", allow_disk=True)
    assert "not a module reference of that Game" in editor.cmd(f"RemoveProjectModuleReference -Module 0000000000000001{MODULE_TYPE} -Game {GAME_ASSET}", allow_disk=True)


def test_the_module_commands_need_the_game_they_work_on(editor):
    """The project has no Game of its own (no SetProjectGame, no default): the commands that list or change the modules of a Game are told which."""
    for command in ("ListProjectModuleReferences", f"AddProjectModuleReference -Module {MODULE_ASSET}", f"RemoveProjectModuleReference -Module {MODULE_ASSET}"):
        reply = editor.cmd(command, allow_disk=True)
        assert "required option" in reply or "give the Game" in reply, (command, reply)
    assert "Unable find the command" in editor.cmd("SetProjectGame -Game " + GAME_ASSET, allow_disk=True), "there is no project Game to set"
    assert "not a Game" in editor.cmd(f"ListProjectModuleReferences -Game {MODULE_ASSET}")
    assert "not in the project" in editor.cmd(f"ListProjectModuleReferences -Game 0000000000000001{GAME_TYPE}")


def test_regenerate_project_module_sources_compiles_the_game_again(editor):
    wait_for_pipeline()
    game = game_folder()
    stamp = PROJECT / "Cache" / "Resources" / "Platforms" / "WINDOWS" / "Game" / game.parent.parent.name / game.parent.name / game.name.removesuffix(".desc")
    before = stamp.stat().st_mtime_ns
    assert "queued to compile" in editor.cmd("RegenerateProjectModuleSources", allow_disk=True)
    deadline = time.time() + 30
    while time.time() < deadline and stamp.stat().st_mtime_ns == before:
        time.sleep(0.25)
    assert stamp.stat().st_mtime_ns > before, "the Game was compiled again"


def test_an_old_script_config_is_not_read_any_more(editor):
    """Script.config.txt used to name the project's Game and list the modules of a project from before the Game resource. Nothing reads it now: a file left over makes no Game."""
    games = lambda: sorted(p.name for p in (PROJECT / "Descriptors" / "Game").glob("*/*/*.desc"))
    original = SCRIPT_CONFIG.read_bytes() if SCRIPT_CONFIG.exists() else None
    before = games()
    legacy = (original.decode().split("[ xProperties")[0] if original else "") + (
        '[ xProperties : 2 ]\n{ Name:s                          Value:?                                        }\n//------------------------------  ----------------------------------------------\n'
        f'  "ScriptConfig/ModuleRefs[]"     ;s64       1                                  \n  "ScriptConfig/ModuleRefs[G:0]"  ;full_guid #{MODULE_GUID} #{MODULE_TYPE}\n')
    editor.stop()
    try:
        SCRIPT_CONFIG.write_bytes(legacy.encode())
        editor.start()
        time.sleep(3)
        assert games() == before, "no Game resource is made from the old module list"
        assert project_game(editor)[1] == [MODULE_ASSET], "and the Game that was there is as it was"
    finally:
        editor.stop()
        if original is None:
            SCRIPT_CONFIG.unlink(missing_ok=True)
        else:
            SCRIPT_CONFIG.write_bytes(original)
        editor.start()


# ---- the build of Game.dll ----------------------------------------------------------------------------------------------------------------------------------------------

CONFIGURED = CMAKELISTS.parent / "Build" / "configured.stamp"          # the build of the example Game: its own folder


def play_once(editor):
    """Play is what makes the editor check Game.dll and build it when it is stale; Stop puts the level back."""
    assert editor.cmd("Play").startswith("Play requested")
    editor.wait_play_state("Playing", timeout=240)             # includes the rebuild
    assert editor.cmd("Stop") == "Stop requested"
    editor.wait_play_state("Stopped")


def test_editing_a_source_file_builds_game_dll_without_configuring_cmake_again(editor, game_level, lib):
    """Adding a file changes what the project is made of, so it is configured again. Editing the file does not: only MSBuild runs, and the precompiled header is left alone."""
    name = f"zz_nocfg_{secrets.token_hex(2)}.cpp"
    target = f"-Library {lib} -Asset {MODULE_ASSET}"
    assert editor.cmd(f"AddScriptSourceFile {target} -FileName {name}", allow_disk=True) == ""
    try:
        wait_for_pipeline(60)
        play_once(editor)                                      # the project changed: configured, then built
        configured = CONFIGURED.stat().st_mtime_ns
        pch = CMAKELISTS.parent / "Build" / "CMakeFiles" / "Game.dir" / "cmake_pch.cxx"
        pch_time = pch.stat().st_mtime_ns if pch.exists() else None
        built_before = editor.log_text().count("Game.dll: rebuild succeeded")
        for n in range(2):
            assert editor.cmd(f"SetScriptSourceFileContent {target} -FileName {name} -Content {quote(f'// edit {n}' + chr(10))}", allow_disk=True) == ""
            play_once(editor)
            assert CONFIGURED.stat().st_mtime_ns == configured, "an edit of a source file does not configure the project again"
            assert (pch.stat().st_mtime_ns if pch.exists() else None) == pch_time, "and does not make the precompiled header look changed"
        assert editor.log_text().count("Game.dll: rebuild succeeded") == built_before + 2, "each edit was built"
    finally:
        editor.cmd(f"RemoveScriptSourceFile {target} -FileName {name}", allow_disk=True)


def test_a_cleared_cache_is_made_again_by_the_pipeline(editor):
    """What the Cache holds is made from the descriptors, so deleting it loses nothing: at the next start the pipeline compiles the module and then the Game, and the project comes back
    byte for byte. Nothing in the editor makes the project - this is the rule that makes every other compiled resource."""
    import shutil
    from script_project import MODULE_CMAKE, MODULE_LOG
    wait_for_pipeline()
    game = game_folder()
    game_rest = f"Game/{game.parent.parent.name}/{game.parent.name}/{game.name.removesuffix('.desc')}"
    stamp = PROJECT / "Cache" / "Resources" / "Platforms" / "WINDOWS" / game_rest
    game_log = PROJECT / "Cache" / "Resources" / "Logs" / f"{game_rest}.log"
    before = (CMAKELISTS.read_bytes(), MODULE_CMAKE.read_bytes())
    editor.stop()
    try:
        for file in (CMAKELISTS, MODULE_CMAKE, stamp):
            file.unlink()
        shutil.rmtree(MODULE_LOG.parent), shutil.rmtree(game_log)
        fresh = Editor(DEFAULT_EXE, log_dir=SMOKE_DIR / ".logs" / "cleared_cache")
        fresh.start()
        try:
            wait_for_pipeline(120)
        finally:
            fresh.stop()
        assert (CMAKELISTS.read_bytes(), MODULE_CMAKE.read_bytes()) == before, "the same project, made from the descriptors"
    finally:
        editor.start()


def test_a_dependency_that_is_gone_compiles_the_resource_again_instead_of_ending_the_editor(editor):
    """A cache that lost the log of a module but kept the Game's output (a partial clear) used to end the editor at startup: the pipeline asked the time of the file the Game depends on.
    A dependency that is not there means the resource has to be compiled again, so that is what happens."""
    import os
    import shutil
    from script_project import MODULE_LOG
    os.utime(MODULE_DESCRIPTOR)                                # looks edited: the module is compiled, and it leaves its log
    deadline = time.time() + 60
    while time.time() < deadline and not MODULE_LOG.exists():
        time.sleep(0.25)
    wait_for_pipeline()
    assert MODULE_LOG.exists()
    game = game_folder()
    stamp = PROJECT / "Cache" / "Resources" / "Platforms" / "WINDOWS" / "Game" / game.parent.parent.name / game.parent.name / game.name.removesuffix(".desc")
    settled = stamp.stat().st_mtime_ns
    while True:                                                # the compile of the Game that the module's compile caused is over
        time.sleep(1.5)
        if stamp.stat().st_mtime_ns == settled:
            break
        settled = stamp.stat().st_mtime_ns
    before = settled
    editor.stop()
    try:
        shutil.rmtree(MODULE_LOG.parent)
        fresh = Editor(DEFAULT_EXE, log_dir=SMOKE_DIR / ".logs" / "lost_dependency")
        fresh.start()
        try:
            deadline = time.time() + 60
            while time.time() < deadline and stamp.stat().st_mtime_ns == before:
                time.sleep(0.25)
            assert fresh.alive() and stamp.stat().st_mtime_ns > before, "the editor started, and the Game was compiled again"
            assert project_game(fresh)[0], "and it answers"
        finally:
            fresh.stop()
    finally:
        # put the module's log back the way the pipeline makes it: the module is compiled again (it looks edited)
        editor.start()
        os.utime(MODULE_DESCRIPTOR)
        wait_for_pipeline(120)
